---
- name: Send email to service team / user
  hosts: all
  connection: local
  gather_facts: false
  vars:
    aap_patch_wf_mail_send_to: "{{ system_owner.email }}"
    aap_patch_wf_mail_sender: "{{ smtp_username }}"
    aap_patch_wf_mail_smtp_host: "{{ smtp_host }}"
    aap_patch_wf_mail_smtp_password: "{{ smtp_password }}"
    aap_patch_wf_mail_smtp_port: "{{ smtp_port }}"
    aap_patch_wf_mail_smtp_username: "{{ smtp_username }}"
  tasks:
    - name: Send email
      community.general.mail:
        host: "{{ aap_patch_wf_mail_smtp_host }}"
        port: "{{ aap_patch_wf_mail_smtp_port }}"
        secure: starttls
        username: "{{ aap_patch_wf_mail_smtp_username }}"
        password: "{{ aap_patch_wf_mail_smtp_password }}"
        sender: "Ansible Automation Platform <{{ aap_patch_wf_mail_sender }}>"
        to: "{{ aap_patch_wf_mail_send_to }}"
        subject: "Patch report for system {{ inventory_hostname }}"
        body: "{{ lookup('ansible.builtin.template', 'templates/mail_template.j2') }}"
