---
- name: Create patch workflow
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aap_workflow_organization_name: Test
  tasks:
    - name: Create a workflow job template
      ansible.controller.workflow_job_template:
        name: example-workflow
        description: created by Ansible Playbook
        organization: Default

    - name: Create input sanitize job template
      ansible.controller.job_template:
        name: "patch_workflow_check_input"
        description: "Sanitize checks"
        job_type: "run"
        organization: "{{ aap_workflow_organization_name }}"
        inventory: "test_inventory"
        project: "{{ test_aap_project_name }}"
        playbook: "patch_workflow_input_sanitize.yml"
        state: "present"
