---
- name: Create patch workflow
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aap_workflow_organization_name: Test
  tasks:
    - name: Update project
      ansible.controller.project_update:
        project: "{{ test_aap_project_name }}"

    - name: Create sanitize input job template
      ansible.controller.job_template:
        name: "Patch Workflow Sanitize Input"
        description: "Sanitize Checks"
        job_type: "run"
        organization: "{{ aap_workflow_organization_name }}"
        inventory: "test_inventory"
        project: "{{ test_aap_project_name }}"
        playbook: "playbooks/patch_wf_sanitize_input.yml"
        state: "present"

    - name: Create PRE patching checks
      ansible.controller.job_template:
        name: "PRE patching checks"
        description: "PRE patching checks"
        job_type: "run"
        organization: "{{ aap_workflow_organization_name }}"
        inventory: "test_inventory"
        project: "{{ test_aap_project_name }}"
        playbook: "playbooks/patch_wf_pre_patching_checks.yml"
        state: "present"

    - name: Create Patch job template
      ansible.controller.job_template:
        name: "Patch system"
        description: "Patch the system"
        job_type: "run"
        organization: "{{ aap_workflow_organization_name }}"
        inventory: "test_inventory"
        project: "{{ test_aap_project_name }}"
        playbook: "playbooks/patch_wf_patch_system.yml"
        state: "present"

    - name: Create Reboot job template
      ansible.controller.job_template:
        name: "Reboot system"
        description: "Reboot the system"
        job_type: "run"
        organization: "{{ aap_workflow_organization_name }}"
        inventory: "test_inventory"
        project: "{{ test_aap_project_name }}"
        playbook: "playbooks/patch_wf_reboot_system.yml"
        state: "present"

    - name: Create POST patching checks
      ansible.controller.job_template:
        name: "POST patching checks"
        description: "POST patching checks"
        job_type: "run"
        organization: "{{ aap_workflow_organization_name }}"
        inventory: "test_inventory"
        project: "{{ test_aap_project_name }}"
        playbook: "playbooks/patch_wf_post_patching_checks.yml"
        state: "present"

    # TODO fetch hostnames to update the survey selection field
    - name: Query remote inventory
      set_fact:
        input_target_hosts: host1.example.com

    - name: Create a workflow job template
      ansible.controller.workflow_job_template:
        name: "Patch Workflow"
        description: created by Ansible Playbook
        organization: "{{ aap_workflow_organization_name }}"
        survey_enabled: true
        # survey_spec: "{{ lookup('file', '{{ playbook_dir }}/surveys/survey_spec.json') }}"
        survey_spec:
          name: Survey Example template
          description: Description goes here
          spec:
            - question_name: Target Host
              question_description: What is the hostname?
              required: true
              type: text
              variable: target_hosts
              min: 0
              max: 1024
              default: "{{ input_target_hosts }}"
              choices: ''
              new_question: true
        workflow_nodes:
          - identifier: "Sanitize survey input"
            unified_job_template:
              organization:
                name: "{{ aap_workflow_organization_name }}"
              name: "Patch Workflow Sanitize Input"
              type: job_template
            credentials: []
            related:
              success_nodes:
                - identifier: "Pre-patch reqs and checks"
              failure_nodes: []
              always_nodes: []
              credentials: []
          - identifier: "Pre-patch reqs and checks"
            unified_job_template:
              organization:
                name: "{{ aap_workflow_organization_name }}"
              name: "PRE patching checks"
              type: job_template
            credentials: []
            related:
              success_nodes:
                - identifier: "Patching"
              failure_nodes: []
              always_nodes: []
              credentials: []
          - identifier: "Patching"
            unified_job_template:
              organization:
                name: "{{ aap_workflow_organization_name }}"
              name: "Patch system"
              type: job_template
            credentials: []
            related:
              success_nodes:
                - identifier: "Reboot"
              failure_nodes: []
              always_nodes: []
              credentials: []
          - identifier: "Reboot"
            unified_job_template:
              organization:
                name: "{{ aap_workflow_organization_name }}"
              name: "Reboot system"
              type: job_template
            credentials: []
            related:
              success_nodes:
                - identifier: "Post patching checks"
              failure_nodes: []
              always_nodes: []
              credentials: []
          - identifier: "Post patching checks"
            unified_job_template:
              organization:
                name: "{{ aap_workflow_organization_name }}"
              name: "POST patching checks"
              type: job_template
            credentials: []
            related:
              success_nodes:
                - identifier: "Send email to system owner"
              failure_nodes: []
              always_nodes: []
              credentials: []
          - identifier: "Send email to system owner"
            unified_job_template:
              organization:
                name: "{{ aap_workflow_organization_name }}"
              name: "Patch Workflow Sanitize Input"
              type: job_template
            credentials: []
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials: []
