---
- name: Send email to service team / user
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Send email
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        secure: starttls
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        sender: "{{ aap_workflow_mail_sender }}"
        to: "{{ aap_workflow_mail_send_to }}"
        subject: "Patch report for system {{ inventory_hostname }}"
        body: "{{ lookup('ansible.builtin.template', 'templates/mail_template.j2') }}"
