---
- name: Run PRE patching checks
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install packages needed for pre patch check
      ansible.builtin.dnf:
        name: yum-utils
        state: installed

    - name: Check if restart is needed
      ansible.builtin.command: needs-restarting -r
      register: aap_patch_wf_needs_restarting
      ignore_errors: true

    - name: Set reboot fact
      ansible.builtin.set_fact:
        aap_patch_wf_reboot_required: true
        aap_patch_wf_reboot_required_stdout: "{{ aap_patch_wf_needs_restarting.stdout }}"
      when: aap_patch_wf_needs_restarting.rc == 1
