---
- name: Check input
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: After version 2.7 both 'msg' and 'fail_msg' can customize failing assertion message
      ansible.builtin.assert:
        that:
          - my_param <= 100
          - my_param >= 0
        fail_msg: "'my_param' must be between 0 and 100"
        success_msg: "'my_param' is between 0 and 100"

# - FQDN's uit de survey opschonen
# - Werkende FQDN
# - Zit de FQDN in de dynamic inventory
# Misschien al een ping uitvoeren op de machines voor de zekerheid?
# 
