---
- name: Send email to service team / user
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Send email
      community.general.mail:
        host: "{{ aap_workflow_smtp_server }}"
        port: 587
        secure: starttls
        username: "{{ vault_workflow_smtp_email }}"
        password: "{{ vault_workflow_smtp_password }}"
        sender: "{{ aap_workflow_mail_sender }}"
        to: "{{ aap_workflow_mail_send_to }}"
        subject: "Patch report for system {{ inventory_hostname }}"
        body: "{{ lookup('ansible.builtin.template', 'templates/mail_template.j2') }}"
