---
- name: Test Ansible Automation Platform
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    test_aap_validate_certs: false
  tasks:
    # DELETE
    - name: Delete Ping job template
      ansible.controller.job_template:
        name: "Ping"
        organization: "{{ test_aap_organization_name }}"
        project: "{{ test_aap_project_name }}"
        state: "absent"

    - name: Delete an inventory source
      ansible.controller.inventory_source:
        name: "source-inventory"
        inventory: "test_inventory"
        source_project: "{{ test_aap_project_name }}"
        organization: "{{ test_aap_organization_name }}"
        state: "absent"
      ignore_errors: true

    - name: Delete inventory
      ansible.controller.inventory:
        name: "test_inventory"
        organization: "{{ test_aap_organization_name }}"
        state: "absent"
      ignore_errors: true

    - name: Delete Project
      ansible.controller.project:
        name: "{{ test_aap_project_name }}"
        organization: "{{ test_aap_organization_name }}"
        state: absent

    - name: Delete a SCM credential
      ansible.controller.credential:
        name: "{{ test_aap_git_credential_name }}"
        organization: "{{ test_aap_organization_name }}"
        state: absent
        credential_type: Source Control
        validate_certs: "{{ test_aap_validate_certs }}"

    - name: Delete a Machine credential
      ansible.controller.credential:
        name: "{{ test_aap_machine_credential_name }}"
        organization: "{{ test_aap_organization_name }}"
        state: absent
        credential_type: Machine
        validate_certs: "{{ test_aap_validate_certs }}"

    # CREATE
    - name: Create a SCM credential
      ansible.controller.credential:
        name: "{{ test_aap_git_credential_name }}"
        organization: "{{ test_aap_organization_name }}"
        state: present
        credential_type: Source Control
        inputs:
          username: "{{ test_aap_git_user }}"
          ssh_key_data: "{{ lookup('file', '../secrets/' + test_aap_git_credential_private_key ) }}"
          # ssh_key_unlock: "passphrase"
        validate_certs: "{{ test_aap_validate_certs }}"

    - name: Create a Machine credential
      ansible.controller.credential:
        name: "{{ test_aap_machine_credential_name }}"
        organization: "{{ test_aap_organization_name }}"
        state: present
        credential_type: Machine
        inputs:
          username: "{{ test_aap_machine_user }}"
          ssh_key_data: "{{ lookup('file', '../secrets/' + test_aap_machine_credential_private_key ) }}"
          # ssh_key_unlock: "passphrase"
        validate_certs: "{{ test_aap_validate_certs }}"

    - name: Create Project
      ansible.controller.project:
        name: "{{ test_aap_project_name }}"
        credential: "{{ test_aap_git_credential_name }}"
        scm_type: git
        scm_url: "{{ test_aap_git_url }}"
        description: "{{ test_aap_project_description }}"
        organization: "{{ test_aap_organization_name }}"
        scm_update_on_launch: false
        scm_update_cache_timeout: 60
        state: present
        validate_certs: "{{ test_aap_validate_certs }}"

    - name: Add inventory
      ansible.controller.inventory:
        name: "test_inventory"
        description: "Test servers inventory"
        organization: "{{ test_aap_organization_name }}"
        state: present
        # controller_config_file: "~/tower_cli.cfg"

    - name: Add an inventory source
      ansible.controller.inventory_source:
        name: "source-inventory"
        source_project: "{{ test_aap_project_name }}"
        description: "Source for test servers inventory"
        inventory: "test_inventory"
        # credential: ""
        overwrite: true
        update_on_launch: true
        organization: "{{ test_aap_organization_name }}"
        source: scm
        source_path: "inventory/hosts"

    - name: Create Ping job template
      ansible.controller.job_template:
        name: "Ping"
        job_type: "run"
        organization: "{{ test_aap_organization_name }}"
        inventory: "test_inventory"
        project: "{{ test_aap_project_name }}"
        playbook: "playbooks/ping.yml"
        credentials: "{{ test_aap_machine_credential_name }}"
        state: "present"

    - name: Launch a job
      ansible.controller.job_launch:
        job_template: "Ping"
